'$schema' = 'https://yazi-rs.github.io/schemas/keymap.json'

[manager]
prepend_keymap = [
  { on = 'Z', run = 'plugin fzf', desc = 'Jump to a file/directory via fzf' },
  { on = 'z', run = 'plugin zoxide', desc = 'Jump to a directory via zoxide' },
]

append_keymap = [
  { on = [
    'g',
    'p',
  ], run = 'cd ~/projects', desc = 'Go ~/projects' },
]
